package newpackage;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author DJay
 */
public class CameraScanForm extends javax.swing.JFrame implements Runnable, ThreadFactory {
    //declare variables
    private WebcamPanel panel = null;
    private Webcam webcam = null;
    String reason, infoname, infoage, infoaddress, infoyearstay;
    String[] residentinfo;
    //private static final long serialVersionUID = 6441489157408381878L;
    private Executor executor = Executors.newSingleThreadExecutor(this);

    //Create current date for documents
    Date thisDate = new Date();
    SimpleDateFormat dateForm = new SimpleDateFormat("MM/dd/Y");
    SimpleDateFormat month = new SimpleDateFormat("MMMM");
    SimpleDateFormat day = new SimpleDateFormat("dd");
    SimpleDateFormat year = new SimpleDateFormat("Y");
    
    /**
     * Creates new form CameraScanForm
     */
    public CameraScanForm() { //call necesarry methods
        initComponents();
        initWebcam();
        choosedocpanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblResidentsData = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        lblDashboard = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        choosedocpanel = new javax.swing.JPanel();
        brdchoosereason = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelchoose = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        rdreason7 = new javax.swing.JRadioButton();
        rdreason6 = new javax.swing.JRadioButton();
        rdreason5 = new javax.swing.JRadioButton();
        rdreason4 = new javax.swing.JRadioButton();
        rdreason3 = new javax.swing.JRadioButton();
        rdreason2 = new javax.swing.JRadioButton();
        rdreason1 = new javax.swing.JRadioButton();
        brdchoosedoc = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnCOI = new javax.swing.JPanel();
        lblCOI = new javax.swing.JLabel();
        btnCOR = new javax.swing.JPanel();
        lblCOR = new javax.swing.JLabel();
        btnBC = new javax.swing.JPanel();
        lblBC = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        printpanel = new javax.swing.JPanel();
        indigencypanel = new javax.swing.JPanel();
        COIeditdate = new javax.swing.JTextField();
        COIedityear = new javax.swing.JTextField();
        COIeditday = new javax.swing.JTextField();
        COIeditmonth = new javax.swing.JTextField();
        COIeditreason = new javax.swing.JTextField();
        COIeditaddress = new javax.swing.JTextField();
        COIeditage = new javax.swing.JTextField();
        COIeditname = new javax.swing.JTextField();
        docindigency = new javax.swing.JLabel();
        residencypanel = new javax.swing.JPanel();
        COReditname3 = new javax.swing.JTextField();
        COReditdate = new javax.swing.JTextField();
        CORedityear = new javax.swing.JTextField();
        COReditday = new javax.swing.JTextField();
        COReditmonth = new javax.swing.JTextField();
        COReditreason = new javax.swing.JTextField();
        COReditname2 = new javax.swing.JTextField();
        COReditaddress = new javax.swing.JTextField();
        COReditstay = new javax.swing.JTextField();
        COReditage = new javax.swing.JTextField();
        COReditname1 = new javax.swing.JTextField();
        docresidency = new javax.swing.JLabel();
        clearancepanel = new javax.swing.JPanel();
        COCeditname2 = new javax.swing.JTextField();
        COCeditdate = new javax.swing.JTextField();
        COCedityear = new javax.swing.JTextField();
        COCeditday = new javax.swing.JTextField();
        COCeditmonth = new javax.swing.JTextField();
        COCeditreason = new javax.swing.JTextField();
        COCeditstay = new javax.swing.JTextField();
        COCeditaddress = new javax.swing.JTextField();
        COCeditage = new javax.swing.JTextField();
        COCeditname1 = new javax.swing.JTextField();
        docclearance = new javax.swing.JLabel();
        btnChangeText = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        scanqrpanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        brdwebcam = new javax.swing.JPanel();
        lbinstruction = new javax.swing.JLabel();
        panelwebcam = new javax.swing.JPanel();
        result_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Scan QR Code");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Barangay Fatima 1");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        lblResidentsData.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 30)); // NOI18N
        lblResidentsData.setForeground(new java.awt.Color(255, 255, 255));
        lblResidentsData.setText("Residents Data");
        lblResidentsData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblResidentsDataMouseClicked(evt);
            }
        });
        jPanel7.add(lblResidentsData, new org.netbeans.lib.awtextra.AbsoluteConstraints(962, 3, -1, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/topnavlogo.png"))); // NOI18N
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblLogout.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 30)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setText("Log Out");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });
        jPanel7.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1271, 3, -1, 80));

        lblDashboard.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 30)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboard.setText("Dashboard");
        lblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashboardMouseClicked(evt);
            }
        });
        jPanel7.add(lblDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 2, -1, 80));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/topnavbg.png"))); // NOI18N
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        choosedocpanel.setBackground(new java.awt.Color(255, 255, 255));
        choosedocpanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                choosedocpanelComponentShown(evt);
            }
        });
        choosedocpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        brdchoosereason.setBackground(new java.awt.Color(255, 255, 255));
        brdchoosereason.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(104, 185, 225), 3, true));
        brdchoosereason.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei", 1, 20)); // NOI18N
        jLabel12.setText("<html>Ano ang layunin ng residente sa pagkuha ng dokumento?</html>");
        brdchoosereason.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 430, -1));

        jLabel14.setFont(new java.awt.Font("Microsoft YaHei", 0, 17)); // NOI18N
        jLabel14.setText("<html>What is the resident's purpose in obtaining the document?</html>");
        brdchoosereason.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 430, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(104, 185, 225)));
        jScrollPane1.setHorizontalScrollBar(null);

        panelchoose.setBackground(new java.awt.Color(255, 255, 255));
        panelchoose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rdreason7.setFont(new java.awt.Font("Microsoft YaHei", 1, 15)); // NOI18N
        rdreason7.setText("EMPLOYMENT");
        rdreason7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdreason7ActionPerformed(evt);
            }
        });
        jPanel3.add(rdreason7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 200, -1));

        rdreason6.setFont(new java.awt.Font("Microsoft YaHei", 1, 15)); // NOI18N
        rdreason6.setText("POLICE CLEARANCE");
        rdreason6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdreason6ActionPerformed(evt);
            }
        });
        jPanel3.add(rdreason6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        rdreason5.setFont(new java.awt.Font("Microsoft YaHei", 1, 15)); // NOI18N
        rdreason5.setText("EDUCATIONAL ASSISTANCE");
        rdreason5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdreason5ActionPerformed(evt);
            }
        });
        jPanel3.add(rdreason5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        rdreason4.setFont(new java.awt.Font("Microsoft YaHei", 1, 15)); // NOI18N
        rdreason4.setText("CASH ASSISTANCE");
        rdreason4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdreason4ActionPerformed(evt);
            }
        });
        jPanel3.add(rdreason4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        rdreason3.setFont(new java.awt.Font("Microsoft YaHei", 1, 15)); // NOI18N
        rdreason3.setText("MEDICAL ASSISTANCE");
        rdreason3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdreason3ActionPerformed(evt);
            }
        });
        jPanel3.add(rdreason3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        rdreason2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 15)); // NOI18N
        rdreason2.setText("FOOD ASSISTANCE");
        rdreason2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdreason2ActionPerformed(evt);
            }
        });
        jPanel3.add(rdreason2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        rdreason1.setFont(new java.awt.Font("Microsoft YaHei", 1, 15)); // NOI18N
        rdreason1.setText("SCHOLARSHIP");
        rdreason1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdreason1ActionPerformed(evt);
            }
        });
        jPanel3.add(rdreason1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        panelchoose.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 310));

        jScrollPane1.setViewportView(panelchoose);

        brdchoosereason.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 430, 240));

        choosedocpanel.add(brdchoosereason, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 500, 470, 390));

        brdchoosedoc.setBackground(new java.awt.Color(255, 255, 255));
        brdchoosedoc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(104, 185, 225), 3, true));
        brdchoosedoc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei", 1, 20)); // NOI18N
        jLabel11.setText("<html>Ano ang dokumento na kailangan ng residente?</html>");
        brdchoosedoc.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 410, -1));

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei", 0, 17)); // NOI18N
        jLabel10.setText("<html>What document does the resident need?</html>");
        brdchoosedoc.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 430, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCOI.setBackground(new java.awt.Color(13, 76, 146));
        btnCOI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCOIMouseClicked(evt);
            }
        });

        lblCOI.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 28)); // NOI18N
        lblCOI.setForeground(new java.awt.Color(255, 255, 255));
        lblCOI.setText("Certificate of Indigency");

        javax.swing.GroupLayout btnCOILayout = new javax.swing.GroupLayout(btnCOI);
        btnCOI.setLayout(btnCOILayout);
        btnCOILayout.setHorizontalGroup(
            btnCOILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCOILayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblCOI)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        btnCOILayout.setVerticalGroup(
            btnCOILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCOILayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(lblCOI)
                .addGap(25, 25, 25))
        );

        jPanel4.add(btnCOI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 90));

        btnCOR.setBackground(new java.awt.Color(255, 255, 255));
        btnCOR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(13, 76, 146), 3));
        btnCOR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCORMouseClicked(evt);
            }
        });

        lblCOR.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 28)); // NOI18N
        lblCOR.setForeground(new java.awt.Color(13, 76, 146));
        lblCOR.setText("Certificate of Residency");

        javax.swing.GroupLayout btnCORLayout = new javax.swing.GroupLayout(btnCOR);
        btnCOR.setLayout(btnCORLayout);
        btnCORLayout.setHorizontalGroup(
            btnCORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCORLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblCOR)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        btnCORLayout.setVerticalGroup(
            btnCORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCORLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblCOR)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel4.add(btnCOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 430, 90));

        btnBC.setBackground(new java.awt.Color(13, 76, 146));
        btnBC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBCMouseClicked(evt);
            }
        });

        lblBC.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 28)); // NOI18N
        lblBC.setForeground(new java.awt.Color(255, 255, 255));
        lblBC.setText("Barangay Clearance");

        javax.swing.GroupLayout btnBCLayout = new javax.swing.GroupLayout(btnBC);
        btnBC.setLayout(btnBCLayout);
        btnBCLayout.setHorizontalGroup(
            btnBCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBCLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lblBC)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        btnBCLayout.setVerticalGroup(
            btnBCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBCLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblBC)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel4.add(btnBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 430, 90));

        brdchoosedoc.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 430, 270));

        choosedocpanel.add(brdchoosedoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 95, 470, 390));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(104, 185, 225)));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        printpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        indigencypanel.setBackground(new java.awt.Color(255, 255, 255));
        indigencypanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        COIeditdate.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        COIeditdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COIeditdate.setText("00/00/0000");
        COIeditdate.setBorder(null);
        indigencypanel.add(COIeditdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 772, 70, 10));

        COIedityear.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        COIedityear.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COIedityear.setText("0000");
        COIedityear.setBorder(null);
        indigencypanel.add(COIedityear, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 587, 40, 15));

        COIeditday.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        COIeditday.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COIeditday.setText("00");
        COIeditday.setBorder(null);
        indigencypanel.add(COIeditday, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 587, 30, 15));

        COIeditmonth.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        COIeditmonth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COIeditmonth.setText("Month");
        COIeditmonth.setBorder(null);
        indigencypanel.add(COIeditmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 587, 110, 15));

        COIeditreason.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        COIeditreason.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COIeditreason.setText("Reason");
        COIeditreason.setBorder(null);
        indigencypanel.add(COIeditreason, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 544, 220, 20));

        COIeditaddress.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        COIeditaddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COIeditaddress.setText("Address");
        COIeditaddress.setBorder(null);
        indigencypanel.add(COIeditaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 230, 15));

        COIeditage.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        COIeditage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COIeditage.setText("00");
        COIeditage.setBorder(null);
        indigencypanel.add(COIeditage, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 355, 30, 15));

        COIeditname.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        COIeditname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COIeditname.setText("Name");
        COIeditname.setAlignmentY(1.0F);
        COIeditname.setBorder(null);
        indigencypanel.add(COIeditname, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 355, 240, 15));

        docindigency.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/indigency.png"))); // NOI18N
        indigencypanel.add(docindigency, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        printpanel.add(indigencypanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 816, 1056));

        residencypanel.setBackground(new java.awt.Color(255, 255, 255));
        residencypanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        COReditname3.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        COReditname3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COReditname3.setText("NAME");
        COReditname3.setAlignmentY(1.0F);
        COReditname3.setBorder(null);
        residencypanel.add(COReditname3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 822, 210, 15));

        COReditdate.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        COReditdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COReditdate.setText("00/00/0000");
        COReditdate.setBorder(null);
        residencypanel.add(COReditdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 685, 70, 10));

        CORedityear.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        CORedityear.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CORedityear.setText("0000");
        CORedityear.setBorder(null);
        residencypanel.add(CORedityear, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 517, 40, 15));

        COReditday.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        COReditday.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COReditday.setText("00");
        COReditday.setBorder(null);
        residencypanel.add(COReditday, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 517, 30, 15));

        COReditmonth.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        COReditmonth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COReditmonth.setText("Month");
        COReditmonth.setBorder(null);
        residencypanel.add(COReditmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 517, 110, 15));

        COReditreason.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        COReditreason.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COReditreason.setText("Reason");
        COReditreason.setBorder(null);
        residencypanel.add(COReditreason, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 467, 240, 20));

        COReditname2.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        COReditname2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COReditname2.setText("Name");
        COReditname2.setAlignmentY(1.0F);
        COReditname2.setBorder(null);
        residencypanel.add(COReditname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 427, 220, 15));

        COReditaddress.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        COReditaddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COReditaddress.setText("Address");
        COReditaddress.setBorder(null);
        residencypanel.add(COReditaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 322, 200, 15));

        COReditstay.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        COReditstay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COReditstay.setText("0000");
        COReditstay.setBorder(null);
        residencypanel.add(COReditstay, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 345, 47, 15));

        COReditage.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        COReditage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COReditage.setText("00");
        COReditage.setBorder(null);
        residencypanel.add(COReditage, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 30, 15));

        COReditname1.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        COReditname1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COReditname1.setText("Name");
        COReditname1.setAlignmentY(1.0F);
        COReditname1.setBorder(null);
        residencypanel.add(COReditname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 299, 230, 15));

        docresidency.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/residency.png"))); // NOI18N
        residencypanel.add(docresidency, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        printpanel.add(residencypanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 816, 1056));

        clearancepanel.setBackground(new java.awt.Color(255, 255, 255));
        clearancepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        COCeditname2.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        COCeditname2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COCeditname2.setText("NAME");
        COCeditname2.setAlignmentY(1.0F);
        COCeditname2.setBorder(null);
        clearancepanel.add(COCeditname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 834, 210, 20));

        COCeditdate.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        COCeditdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COCeditdate.setText("00/00/0000");
        COCeditdate.setBorder(null);
        clearancepanel.add(COCeditdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 712, 70, 10));

        COCedityear.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        COCedityear.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COCedityear.setText("0000");
        COCedityear.setBorder(null);
        clearancepanel.add(COCedityear, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 534, 50, 15));

        COCeditday.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        COCeditday.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COCeditday.setText("00");
        COCeditday.setBorder(null);
        clearancepanel.add(COCeditday, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 534, 40, 15));

        COCeditmonth.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        COCeditmonth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COCeditmonth.setText("Month");
        COCeditmonth.setBorder(null);
        clearancepanel.add(COCeditmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 534, 92, 15));

        COCeditreason.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        COCeditreason.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COCeditreason.setText("Reason");
        COCeditreason.setBorder(null);
        clearancepanel.add(COCeditreason, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 497, 240, 20));

        COCeditstay.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        COCeditstay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COCeditstay.setText("0000");
        COCeditstay.setBorder(null);
        clearancepanel.add(COCeditstay, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 375, 49, 15));

        COCeditaddress.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        COCeditaddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COCeditaddress.setText("Address");
        COCeditaddress.setBorder(null);
        clearancepanel.add(COCeditaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 352, 208, 15));

        COCeditage.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        COCeditage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COCeditage.setText("00");
        COCeditage.setBorder(null);
        clearancepanel.add(COCeditage, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 307, 30, 15));

        COCeditname1.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        COCeditname1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COCeditname1.setText("Name");
        COCeditname1.setAlignmentY(1.0F);
        COCeditname1.setBorder(null);
        clearancepanel.add(COCeditname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 307, 235, 15));

        docclearance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/clearance.png"))); // NOI18N
        clearancepanel.add(docclearance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        printpanel.add(clearancepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 816, 1056));

        jScrollPane2.setViewportView(printpanel);

        choosedocpanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 93, -1, 720));

        btnChangeText.setBackground(new java.awt.Color(13, 76, 146));
        btnChangeText.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        btnChangeText.setForeground(new java.awt.Color(255, 255, 255));
        btnChangeText.setText("CHANGE TEXT");
        btnChangeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeTextActionPerformed(evt);
            }
        });
        choosedocpanel.add(btnChangeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 830, 200, 50));

        btnPrint.setBackground(new java.awt.Color(13, 76, 146));
        btnPrint.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setText("SAVE OR PRINT DOCUMENT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        choosedocpanel.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 830, 340, 50));

        jPanel7.add(choosedocpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 900));

        scanqrpanel.setBackground(new java.awt.Color(255, 255, 255));
        scanqrpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei", 1, 32)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(3, 87, 122));
        jLabel13.setText("| Scan QR Code");
        scanqrpanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        brdwebcam.setBackground(new java.awt.Color(255, 255, 255));
        brdwebcam.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(104, 185, 225), 3, true));
        brdwebcam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbinstruction.setFont(new java.awt.Font("Microsoft YaHei", 0, 20)); // NOI18N
        lbinstruction.setText("<html><center><strong>Isakto sa frame ng camera ang QR code.</strong>\n<br>Please place the QR code inside the camera frame.</center><html>");
        brdwebcam.add(lbinstruction, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        panelwebcam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        brdwebcam.add(panelwebcam, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 511, 310));

        result_field.setFont(new java.awt.Font("Microsoft YaHei", 0, 15)); // NOI18N
        result_field.setText("Result");
        result_field.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        brdwebcam.add(result_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 510, 50));

        scanqrpanel.add(brdwebcam, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 590, 500));

        jPanel7.add(scanqrpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 900));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 900));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void initWebcam() { //execute webcam
        Dimension size = WebcamResolution.QVGA.getSize();
        webcam = Webcam.getWebcams().get(0);
        webcam.setViewSize(size);

        panel = new WebcamPanel(webcam);
        panel.setPreferredSize(size);
        panel.setFPSDisplayed(true);

        panelwebcam.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 310));

        executor.execute(this);
    }
    @Override
    public void run() { //scan and get data from QR code
        Result result = null;
        BufferedImage image = null;

        do {
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

            try {
                if (webcam.isOpen()) {
                    if ((image = webcam.getImage()) == null) {
                        continue;  
                    }
                    LuminanceSource source = new BufferedImageLuminanceSource(image);
                    BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));

                    result = new MultiFormatReader().decode(bitmap);
                }
            } catch (NotFoundException e) {
                //JOptionPane.showMessageDialog(null, e);
            } finally {
                //webcam.close();
            } 
//            if (webcam.isOpen()) {
//                if ((image = webcam.getImage()) == null) {
//                    continue;
//                } 
//            }else {
//                webcam.close();
//            }
//
//            LuminanceSource source = new BufferedImageLuminanceSource(image);
//            BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));
//
//            try {
//                result = new MultiFormatReader().decode(bitmap);
//            } catch (NotFoundException e) {
//                //No result
//            }
            
            if (result != null) { //split data from QR code
                //result_field.setText(result.getText());
                result.getText();
                String text = result.toString();
                residentinfo = text.split(";");
                infoname = residentinfo[0];
                infoage = residentinfo[1];
                infoaddress = residentinfo[2];
                infoyearstay = residentinfo[3];
                
                choosedocpanel.setVisible(true);
                scanqrpanel.setVisible(false);
            }
        } while(true);
    }

    @Override
    public Thread newThread(Runnable r) {
        Thread t = new Thread(r, "My Thread");
        t.setDaemon(true);
        return t;
    }

    private void printDocument(JPanel panel){ //save or print document
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        printerJob.setJobName("Print Document");

        printerJob.setPrintable(new Printable() {
            /*@Override*/
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if(pageIndex > 0) {
                    return Printable.NO_SUCH_PAGE;
                }
            
            Graphics2D graphics2D = (Graphics2D) graphics;
            graphics2D.translate(pageFormat.getImageableX()*2, pageFormat.getImageableY()*2);
            graphics2D.scale(0.75, 0.75);

            panel.paint(graphics2D);

            return Printable.PAGE_EXISTS;
            }
        });
        
        boolean returningResult = printerJob.printDialog();

        if(returningResult) {
            try{
                printerJob.print();
            }catch (PrinterException printerException){
                JOptionPane.showMessageDialog(this, "Print Error: " + printerException.getMessage());
            }
        }
    }

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        //call print method
        printDocument(printpanel);
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnBCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBCMouseClicked
        //show clearance panel
        indigencypanel.setVisible(false);
        residencypanel.setVisible(false);
        clearancepanel.setVisible(true);
    }//GEN-LAST:event_btnBCMouseClicked

    private void btnCORMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCORMouseClicked
        //show residency panel
        indigencypanel.setVisible(false);
        residencypanel.setVisible(true);
        clearancepanel.setVisible(false);
    }//GEN-LAST:event_btnCORMouseClicked

    private void btnCOIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCOIMouseClicked
        //show indigency panel
        indigencypanel.setVisible(true);
        residencypanel.setVisible(false);
        clearancepanel.setVisible(false);
    }//GEN-LAST:event_btnCOIMouseClicked

    private void rdreason1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdreason1ActionPerformed
        //set text to SCHOLARSHIP if radio1 was clicked
        reason = "SCHOLARSHIP";
        if(rdreason1.isSelected()){
            rdreason2.setSelected(false);
            rdreason3.setSelected(false);
            rdreason4.setSelected(false);
            rdreason5.setSelected(false);
            rdreason6.setSelected(false);
            rdreason7.setSelected(false);

            COIeditreason.setText(reason);
            COReditreason.setText(reason);
            COCeditreason.setText(reason);
        }
    }//GEN-LAST:event_rdreason1ActionPerformed

    private void rdreason2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdreason2ActionPerformed
        //set text to FOOD ASSISTANCE if radio2 was clicked
        reason = "FOOD ASSISTANCE";
        if(rdreason2.isSelected()){
            rdreason1.setSelected(false);
            rdreason3.setSelected(false);
            rdreason4.setSelected(false);
            rdreason5.setSelected(false);
            rdreason6.setSelected(false);
            rdreason7.setSelected(false);

            COIeditreason.setText(reason);
            COReditreason.setText(reason);
            COCeditreason.setText(reason);
        }
    }//GEN-LAST:event_rdreason2ActionPerformed

    private void rdreason3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdreason3ActionPerformed
        //set text to MEDICAL ASSISTANCE if radio3 was clicked
        reason = "MEDICAL ASSISTANCE";
        if(rdreason3.isSelected()){
            rdreason1.setSelected(false);
            rdreason2.setSelected(false);
            rdreason4.setSelected(false);
            rdreason5.setSelected(false);
            rdreason6.setSelected(false);
            rdreason7.setSelected(false);

            COIeditreason.setText(reason);
            COReditreason.setText(reason);
            COCeditreason.setText(reason);
        }
    }//GEN-LAST:event_rdreason3ActionPerformed

    private void rdreason4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdreason4ActionPerformed
        //set text to CASH ASSISTANCE if radio4 was clicked
        reason = "CASH ASSISTANCE";
        if(rdreason4.isSelected()){
            rdreason1.setSelected(false);
            rdreason2.setSelected(false);
            rdreason3.setSelected(false);
            rdreason5.setSelected(false);
            rdreason6.setSelected(false);
            rdreason7.setSelected(false);

            COIeditreason.setText(reason);
            COReditreason.setText(reason);
            COCeditreason.setText(reason);
        }
    }//GEN-LAST:event_rdreason4ActionPerformed

    private void rdreason5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdreason5ActionPerformed
        //set text to EDUCATIONAL ASSISTANCE if radio5 was clicked
        reason = "EDUCATIONAL ASSISTANCE";
        if(rdreason5.isSelected()){
            rdreason1.setSelected(false);
            rdreason2.setSelected(false);
            rdreason3.setSelected(false);
            rdreason4.setSelected(false);
            rdreason6.setSelected(false);
            rdreason7.setSelected(false);

            COIeditreason.setText(reason);
            COReditreason.setText(reason);
            COCeditreason.setText(reason);
        }
    }//GEN-LAST:event_rdreason5ActionPerformed

    private void rdreason6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdreason6ActionPerformed
        //set text to POLICE CLEARANCE if radio6 was clicked
        reason = "POLICE CLEARANCE";
        if(rdreason6.isSelected()){
            rdreason1.setSelected(false);
            rdreason2.setSelected(false);
            rdreason3.setSelected(false);
            rdreason4.setSelected(false);
            rdreason5.setSelected(false);
            rdreason7.setSelected(false);

            COIeditreason.setText(reason);
            COReditreason.setText(reason);
            COCeditreason.setText(reason);
        }
    }//GEN-LAST:event_rdreason6ActionPerformed

    private void rdreason7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdreason7ActionPerformed
        //set text to EMPLOYMENT if radio7 was clicked
        reason = "EMPLOYMENT";
        if(rdreason7.isSelected()){
            rdreason1.setSelected(false);
            rdreason2.setSelected(false);
            rdreason3.setSelected(false);
            rdreason4.setSelected(false);
            rdreason5.setSelected(false);
            rdreason6.setSelected(false);

            COIeditreason.setText(reason);
            COReditreason.setText(reason);
            COCeditreason.setText(reason);
        }
    }//GEN-LAST:event_rdreason7ActionPerformed

    private void lblResidentsDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResidentsDataMouseClicked
        //topbar navigation
        ResidentsDataForm rdf = new ResidentsDataForm();
        rdf.show();

        dispose();
    }//GEN-LAST:event_lblResidentsDataMouseClicked

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        //topbar navigation
        LogInForm lif = new LogInForm();
        lif.show();

        dispose();
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseClicked
        //topbar navigation
        DashboardForm dbf = new DashboardForm();
        dbf.show();

        dispose();
    }//GEN-LAST:event_lblDashboardMouseClicked

    private void btnChangeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeTextActionPerformed
        //automatic fill-up if CHANGE TEXT button was clicked
        COIeditname.setText(infoname);
        COIeditage.setText(infoage);
        COIeditaddress.setText(infoaddress);

        COReditname1.setText(infoname);
        COReditname2.setText(infoname);
        COReditname3.setText(infoname);
        COReditage.setText(infoage);
        COReditaddress.setText(infoaddress);
        COReditstay.setText(infoyearstay);

        COCeditname1.setText(infoname);
        COCeditname2.setText(infoname);
        COCeditage.setText(infoage);
        COCeditaddress.setText(infoaddress);
        COCeditstay.setText(infoyearstay);

        COIeditmonth.setText(month.format(thisDate));
        COReditmonth.setText(month.format(thisDate));
        COCeditmonth.setText(month.format(thisDate));

        COIeditday.setText(day.format(thisDate));
        COReditday.setText(day.format(thisDate));
        COCeditday.setText(day.format(thisDate));

        COIedityear.setText(year.format(thisDate));
        CORedityear.setText(year.format(thisDate));
        COCedityear.setText(year.format(thisDate));

        COIeditdate.setText(dateForm.format(thisDate));
        COReditdate.setText(dateForm.format(thisDate));
        COCeditdate.setText(dateForm.format(thisDate));
    }//GEN-LAST:event_btnChangeTextActionPerformed

    private void choosedocpanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_choosedocpanelComponentShown
        //show this message dialog if QR code was scanned successfully
        JOptionPane.showMessageDialog(this, "Data from QR code was scanned successfully.\n"
            + "Click CHANGE TEXT button to automatically fill-up the document.");
    }//GEN-LAST:event_choosedocpanelComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CameraScanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CameraScanForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField COCeditaddress;
    private javax.swing.JTextField COCeditage;
    private javax.swing.JTextField COCeditdate;
    private javax.swing.JTextField COCeditday;
    private javax.swing.JTextField COCeditmonth;
    private javax.swing.JTextField COCeditname1;
    private javax.swing.JTextField COCeditname2;
    private javax.swing.JTextField COCeditreason;
    private javax.swing.JTextField COCeditstay;
    private javax.swing.JTextField COCedityear;
    private javax.swing.JTextField COIeditaddress;
    private javax.swing.JTextField COIeditage;
    private javax.swing.JTextField COIeditdate;
    private javax.swing.JTextField COIeditday;
    private javax.swing.JTextField COIeditmonth;
    private javax.swing.JTextField COIeditname;
    private javax.swing.JTextField COIeditreason;
    private javax.swing.JTextField COIedityear;
    private javax.swing.JTextField COReditaddress;
    private javax.swing.JTextField COReditage;
    private javax.swing.JTextField COReditdate;
    private javax.swing.JTextField COReditday;
    private javax.swing.JTextField COReditmonth;
    private javax.swing.JTextField COReditname1;
    private javax.swing.JTextField COReditname2;
    private javax.swing.JTextField COReditname3;
    private javax.swing.JTextField COReditreason;
    private javax.swing.JTextField COReditstay;
    private javax.swing.JTextField CORedityear;
    private javax.swing.JPanel brdchoosedoc;
    private javax.swing.JPanel brdchoosereason;
    private javax.swing.JPanel brdwebcam;
    private javax.swing.JPanel btnBC;
    private javax.swing.JPanel btnCOI;
    private javax.swing.JPanel btnCOR;
    private javax.swing.JButton btnChangeText;
    private javax.swing.JButton btnPrint;
    private javax.swing.JPanel choosedocpanel;
    private javax.swing.JPanel clearancepanel;
    private javax.swing.JLabel docclearance;
    private javax.swing.JLabel docindigency;
    private javax.swing.JLabel docresidency;
    private javax.swing.JPanel indigencypanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbinstruction;
    private javax.swing.JLabel lblBC;
    private javax.swing.JLabel lblCOI;
    private javax.swing.JLabel lblCOR;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblResidentsData;
    private javax.swing.JPanel panelchoose;
    private javax.swing.JPanel panelwebcam;
    private javax.swing.JPanel printpanel;
    private javax.swing.JRadioButton rdreason1;
    private javax.swing.JRadioButton rdreason2;
    private javax.swing.JRadioButton rdreason3;
    private javax.swing.JRadioButton rdreason4;
    private javax.swing.JRadioButton rdreason5;
    private javax.swing.JRadioButton rdreason6;
    private javax.swing.JRadioButton rdreason7;
    private javax.swing.JPanel residencypanel;
    private javax.swing.JTextField result_field;
    private javax.swing.JPanel scanqrpanel;
    // End of variables declaration//GEN-END:variables
}
