/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpackage;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author DJay
 */
public class ChooseDocumentForm extends javax.swing.JFrame {

    /**
     * Creates new form ChooseDocumentForm
     */
    public ChooseDocumentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        brdchoosedoc = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnCOI = new javax.swing.JPanel();
        lblCOI = new javax.swing.JLabel();
        btnCOR = new javax.swing.JPanel();
        lblCOR = new javax.swing.JLabel();
        btnBC = new javax.swing.JPanel();
        lblBC = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        printpanel = new javax.swing.JPanel();
        indigencypanel = new javax.swing.JPanel();
        COIeditfor = new javax.swing.JTextField();
        COIeditaddress = new javax.swing.JTextField();
        COIeditage = new javax.swing.JTextField();
        COIeditname = new javax.swing.JTextField();
        docindigency = new javax.swing.JLabel();
        residencypanel = new javax.swing.JPanel();
        docresidency = new javax.swing.JLabel();
        clearancepanel = new javax.swing.JPanel();
        docclearance = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Barangay Fatima 1");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/topnavlogo.png"))); // NOI18N
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/topnavbg.png"))); // NOI18N
        jLabel18.setText("  ");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 85));

        brdchoosedoc.setBackground(new java.awt.Color(255, 255, 255));
        brdchoosedoc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(104, 185, 225), 3, true));
        brdchoosedoc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei", 1, 20)); // NOI18N
        jLabel11.setText("<html>Pumili ng dokumento na kailangan ng residente.</html>");
        brdchoosedoc.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 410, -1));

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei", 0, 17)); // NOI18N
        jLabel10.setText("<html>Choose a document that the resident needs.</html>");
        brdchoosedoc.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 550, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCOI.setBackground(new java.awt.Color(13, 76, 146));
        btnCOI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCOIMouseClicked(evt);
            }
        });

        lblCOI.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 28)); // NOI18N
        lblCOI.setForeground(new java.awt.Color(255, 255, 255));
        lblCOI.setText("Certificate of Indigency");

        javax.swing.GroupLayout btnCOILayout = new javax.swing.GroupLayout(btnCOI);
        btnCOI.setLayout(btnCOILayout);
        btnCOILayout.setHorizontalGroup(
            btnCOILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCOILayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblCOI)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        btnCOILayout.setVerticalGroup(
            btnCOILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCOILayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(lblCOI)
                .addGap(25, 25, 25))
        );

        jPanel3.add(btnCOI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 90));

        btnCOR.setBackground(new java.awt.Color(255, 255, 255));
        btnCOR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(13, 76, 146), 3));
        btnCOR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCORMouseClicked(evt);
            }
        });

        lblCOR.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 28)); // NOI18N
        lblCOR.setForeground(new java.awt.Color(13, 76, 146));
        lblCOR.setText("Certificate of Residency");

        javax.swing.GroupLayout btnCORLayout = new javax.swing.GroupLayout(btnCOR);
        btnCOR.setLayout(btnCORLayout);
        btnCORLayout.setHorizontalGroup(
            btnCORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCORLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblCOR)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        btnCORLayout.setVerticalGroup(
            btnCORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCORLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblCOR)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.add(btnCOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 430, 90));

        btnBC.setBackground(new java.awt.Color(13, 76, 146));
        btnBC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBCMouseClicked(evt);
            }
        });

        lblBC.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 28)); // NOI18N
        lblBC.setForeground(new java.awt.Color(255, 255, 255));
        lblBC.setText("Barangay Clearance");

        javax.swing.GroupLayout btnBCLayout = new javax.swing.GroupLayout(btnBC);
        btnBC.setLayout(btnBCLayout);
        btnBCLayout.setHorizontalGroup(
            btnBCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBCLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lblBC)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        btnBCLayout.setVerticalGroup(
            btnBCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBCLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblBC)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.add(btnBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 430, 90));

        brdchoosedoc.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 430, 270));

        jPanel1.add(brdchoosedoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 470, 390));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        printpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        indigencypanel.setBackground(new java.awt.Color(255, 255, 255));
        indigencypanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        COIeditfor.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        COIeditfor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COIeditfor.setText("For");
        COIeditfor.setBorder(null);
        COIeditfor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COIeditforActionPerformed(evt);
            }
        });
        indigencypanel.add(COIeditfor, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 544, 220, 20));

        COIeditaddress.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        COIeditaddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COIeditaddress.setText("Address");
        COIeditaddress.setBorder(null);
        COIeditaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COIeditaddressActionPerformed(evt);
            }
        });
        indigencypanel.add(COIeditaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 230, 15));

        COIeditage.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        COIeditage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COIeditage.setText("00");
        COIeditage.setBorder(null);
        COIeditage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COIeditageActionPerformed(evt);
            }
        });
        indigencypanel.add(COIeditage, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, 30, 20));

        COIeditname.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        COIeditname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        COIeditname.setText("Name");
        COIeditname.setAlignmentY(1.0F);
        COIeditname.setBorder(null);
        COIeditname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COIeditnameActionPerformed(evt);
            }
        });
        indigencypanel.add(COIeditname, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 240, 20));

        docindigency.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/indigency.png"))); // NOI18N
        indigencypanel.add(docindigency, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        printpanel.add(indigencypanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 816, 1056));

        residencypanel.setBackground(new java.awt.Color(255, 255, 255));
        residencypanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        docresidency.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/residency.png"))); // NOI18N
        residencypanel.add(docresidency, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        printpanel.add(residencypanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 816, 1056));

        clearancepanel.setBackground(new java.awt.Color(255, 255, 255));
        clearancepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        docclearance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/clearance.png"))); // NOI18N
        clearancepanel.add(docclearance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        printpanel.add(clearancepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 816, 1056));

        jScrollPane2.setViewportView(printpanel);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 93, -1, 720));

        btnPrint.setBackground(new java.awt.Color(13, 76, 146));
        btnPrint.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 830, 140, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCOIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCOIMouseClicked
        // TODO add your handling code here:
        indigencypanel.setVisible(true);
        residencypanel.setVisible(false);
        clearancepanel.setVisible(false);
    }//GEN-LAST:event_btnCOIMouseClicked

    private void btnCORMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCORMouseClicked
        // TODO add your handling code here:
        indigencypanel.setVisible(false);
        residencypanel.setVisible(true);
        clearancepanel.setVisible(false);
    }//GEN-LAST:event_btnCORMouseClicked

    private void btnBCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBCMouseClicked
        // TODO add your handling code here:
        indigencypanel.setVisible(false);
        residencypanel.setVisible(false);
        clearancepanel.setVisible(true);
    }//GEN-LAST:event_btnBCMouseClicked

    private void COIeditnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COIeditnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COIeditnameActionPerformed

    private void COIeditageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COIeditageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COIeditageActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        printDocument(printpanel);//call print method
    }//GEN-LAST:event_btnPrintActionPerformed

    private void COIeditaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COIeditaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COIeditaddressActionPerformed

    private void COIeditforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COIeditforActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COIeditforActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseDocumentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseDocumentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseDocumentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseDocumentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseDocumentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField COIeditaddress;
    private javax.swing.JTextField COIeditage;
    private javax.swing.JTextField COIeditfor;
    private javax.swing.JTextField COIeditname;
    private javax.swing.JPanel brdchoosedoc;
    private javax.swing.JPanel btnBC;
    private javax.swing.JPanel btnCOI;
    private javax.swing.JPanel btnCOR;
    private javax.swing.JButton btnPrint;
    private javax.swing.JPanel clearancepanel;
    private javax.swing.JLabel docclearance;
    private javax.swing.JLabel docindigency;
    private javax.swing.JLabel docresidency;
    private javax.swing.JPanel indigencypanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBC;
    private javax.swing.JLabel lblCOI;
    private javax.swing.JLabel lblCOR;
    private javax.swing.JPanel printpanel;
    private javax.swing.JPanel residencypanel;
    // End of variables declaration//GEN-END:variables
    
    private void printDocument(JPanel panel){
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        printerJob.setJobName("Print Document");

        printerJob.setPrintable(new Printable() {
            /*@Override*/
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if(pageIndex > 0) {
                    return Printable.NO_SUCH_PAGE;
                }
            
            Graphics2D graphics2D = (Graphics2D) graphics;
            graphics2D.translate(pageFormat.getImageableX()*2, pageFormat.getImageableY()*2);
            graphics2D.scale(0.75, 0.75);

            panel.paint(graphics2D);

            return Printable.PAGE_EXISTS;
            }
        });
        
        boolean returningResult = printerJob.printDialog();

        if(returningResult) {
            try{
                printerJob.print();
            }catch (PrinterException printerException){
                JOptionPane.showMessageDialog(this, "Print Error: " + printerException.getMessage());
            }
        }
    }
}
