/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpackage;

import javax.swing.JOptionPane;

/**
 *
 * @author DJay
 */
public class SplashScreenForm extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreenForm
     */
    public SplashScreenForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loadbar = new javax.swing.JProgressBar();
        loadpercent = new javax.swing.JLabel();
        loadlabel = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(loadbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 860, 1420, 30));

        loadpercent.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        loadpercent.setForeground(new java.awt.Color(255, 255, 255));
        loadpercent.setText("0%");
        jPanel1.add(loadpercent, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 820, 70, -1));

        loadlabel.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        loadlabel.setForeground(new java.awt.Color(255, 255, 255));
        loadlabel.setText("Loading...");
        jPanel1.add(loadlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 820, -1, -1));

        title.setFont(new java.awt.Font("Microsoft YaHei", 1, 70)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("<html><center>Document Fill-Up Automation System</center></html>");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, 740, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bgloading.png"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreenForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreenForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreenForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreenForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SplashScreenForm().setVisible(true);
//            }
//        });

        SplashScreenForm sp = new SplashScreenForm();
        sp.setVisible(true);
        
        try {
            for (int i = 0; i <= 101; i++) {
                Thread.sleep(100);
                sp.loadpercent.setText(i + "%");
                
                if(i == 10) {
                    sp.loadlabel.setText("Turning on Modules...");
                }
                if(i == 20) {
                    sp.loadlabel.setText("Loading Modules...");
                }
                if(i == 30) {
                    sp.loadlabel.setText("Connecting to Database...");
                }
                if(i == 40) {
                    sp.loadlabel.setText("Connection Successful...");
                }
                if(i == 50) {
                    sp.loadlabel.setText("Setting Camera...");
                }
                if(i == 60) {
                    sp.loadlabel.setText("Setting Successful...");
                }
                if(i == 80) {
                    sp.loadlabel.setText("Launching Application...");
                }
                if(i == 90) {
                    sp.loadlabel.setText("Launch Successful!");
                }
                if (i == 101) {
                    sp.setVisible(false);
                }
                sp.loadbar.setValue(i);
            }
            LogInForm lif = new LogInForm();
            lif.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar loadbar;
    private javax.swing.JLabel loadlabel;
    private javax.swing.JLabel loadpercent;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
