/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fillupautomationsystem.newpackage;

import javax.swing.ButtonGroup;

/**
 *
 * @author Reymart
 */
public class ResidentsDataForm extends javax.swing.JFrame {

    /**
     * Creates new form ResidentsDataForm
     */
    public ResidentsDataForm() {
        initComponents();
        ButtonGroup BtnGrp = new ButtonGroup();
        BtnGrp.add(rbtnMale);
        BtnGrp.add(rbtnFemale);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        headerbg = new javax.swing.JLabel();
        regform = new javax.swing.JPanel();
        regword = new javax.swing.JLabel();
        firstname = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        middleinitial = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        rbtnMale = new javax.swing.JRadioButton();
        rbtnFemale = new javax.swing.JRadioButton();
        jTextField9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        lastname1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        regform1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField5 = new javax.swing.JTextField();
        lastname = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Residents Data");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Logout");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dashboard");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("| Residents Data");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Reymart\\Documents\\GitHub\\document-fill-up-automation-system\\assets\\logo2.png")); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        headerbg.setIcon(new javax.swing.ImageIcon("C:\\Users\\Reymart\\Desktop\\assets\\TopRectangle.png")); // NOI18N
        headerbg.setText("jLabel1");
        jPanel1.add(headerbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, -1));

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        regform.setBackground(new java.awt.Color(255, 255, 255));
        regform.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 3, true));
        regform.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regword.setFont(new java.awt.Font("Rockwell", 0, 30)); // NOI18N
        regword.setForeground(new java.awt.Color(0, 102, 153));
        regword.setText("Registration Form");
        regform.add(regword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        firstname.setFont(new java.awt.Font("Microsoft YaHei", 0, 20)); // NOI18N
        firstname.setText("First Name");
        regform.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 98, 130), 2));
        regform.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 170, 25));

        middleinitial.setFont(new java.awt.Font("Microsoft YaHei", 0, 20)); // NOI18N
        middleinitial.setText("Middle Initial");
        regform.add(middleinitial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 98, 130), 2));
        regform.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 80, 25));

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei", 0, 15)); // NOI18N
        jLabel9.setText("House No.");
        regform.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 98, 130), 2));
        regform.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 170, 25));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 0, 15)); // NOI18N
        jLabel4.setText("Street");
        regform.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 98, 130), 2));
        regform.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 80, 25));

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei", 0, 20)); // NOI18N
        jLabel10.setText("Gender");
        regform.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei", 0, 20)); // NOI18N
        jLabel8.setText("Address");
        regform.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 98, 130), 2));
        regform.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 170, 25));

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei", 0, 20)); // NOI18N
        jLabel11.setText("Contact #");
        regform.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, -1, -1));

        rbtnMale.setBackground(new java.awt.Color(255, 255, 255));
        rbtnMale.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 15)); // NOI18N
        rbtnMale.setText("Male");
        rbtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMaleActionPerformed(evt);
            }
        });
        regform.add(rbtnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        rbtnFemale.setBackground(new java.awt.Color(255, 255, 255));
        rbtnFemale.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 15)); // NOI18N
        rbtnFemale.setText("Female");
        rbtnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFemaleActionPerformed(evt);
            }
        });
        regform.add(rbtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        jTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 98, 130), 2));
        regform.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 170, 25));

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei", 0, 20)); // NOI18N
        jLabel13.setText("Age");
        regform.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jTextField10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 98, 130), 2));
        regform.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 170, 25));

        jLabel14.setFont(new java.awt.Font("Microsoft YaHei", 0, 20)); // NOI18N
        jLabel14.setText("Place of Birth");
        regform.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, -1));

        jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 98, 130), 2));
        regform.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 170, 25));

        jButton5.setBackground(new java.awt.Color(13, 76, 146));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Update");
        regform.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 530, 120, 43));

        jLabel15.setFont(new java.awt.Font("Microsoft YaHei", 0, 20)); // NOI18N
        jLabel15.setText("Years of Stay");
        regform.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        jButton8.setBackground(new java.awt.Color(13, 76, 146));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Upload Image");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        regform.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 140, 43));

        jButton9.setBackground(new java.awt.Color(13, 76, 146));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Clear");
        jButton9.setBorderPainted(false);
        regform.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 120, 43));

        jLabel16.setFont(new java.awt.Font("Microsoft YaHei", 0, 20)); // NOI18N
        jLabel16.setText("Date of Birth");
        regform.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        jTextField12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 98, 130), 2));
        regform.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 170, 25));

        jTextField13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 98, 130), 2));
        regform.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, 25));

        lastname1.setFont(new java.awt.Font("Microsoft YaHei", 0, 20)); // NOI18N
        lastname1.setText("Last Name");
        regform.add(lastname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Reymart\\Documents\\GitHub\\document-fill-up-automation-system\\assets\\DefaultImage.png")); // NOI18N
        jLabel5.setText("jLabel5");
        regform.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 160, 150));

        jButton12.setBackground(new java.awt.Color(13, 76, 146));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Add");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        regform.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 120, 43));

        background.add(regform, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 580, 620));

        regform1.setBackground(new java.awt.Color(255, 255, 255));
        regform1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 3, true));
        regform1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(104, 185, 225), 1, true));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        regform1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 760, 570));

        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 98, 130), 2));
        regform1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 170, 25));

        lastname.setFont(new java.awt.Font("Microsoft YaHei", 0, 17)); // NOI18N
        lastname.setText("Search");
        regform1.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        background.add(regform1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 780, 620));

        jButton7.setBackground(new java.awt.Color(13, 76, 146));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Generet I.D");
        background.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 770, 120, 43));

        jButton10.setBackground(new java.awt.Color(13, 76, 146));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Back");
        background.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 770, 120, 43));

        jButton11.setBackground(new java.awt.Color(13, 76, 146));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Delete");
        background.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 770, 120, 43));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 935, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMaleActionPerformed

    private void rbtnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnFemaleActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResidentsDataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResidentsDataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResidentsDataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResidentsDataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResidentsDataForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel firstname;
    private javax.swing.JLabel headerbg;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lastname;
    private javax.swing.JLabel lastname1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel middleinitial;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.JRadioButton rbtnMale;
    private javax.swing.JPanel regform;
    private javax.swing.JPanel regform1;
    private javax.swing.JLabel regword;
    // End of variables declaration//GEN-END:variables
}
