/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fillupautomationsystem.newpackage;

/**
 *
 * @author Reymart
 */
public class ResidentDataForm extends javax.swing.JFrame {

    /**
     * Creates new form ResidentDataForm
     */
    public ResidentDataForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        headerbg = new javax.swing.JLabel();
        regform = new javax.swing.JPanel();
        regword = new javax.swing.JLabel();
        lastname = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        firstname = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        middleinitial = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        regform1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Logout");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dashboard");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("| Residents Data");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Reymart\\Documents\\GitHub\\document-fill-up-automation-system\\assets\\logo2.png")); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        headerbg.setIcon(new javax.swing.ImageIcon("C:\\Users\\Reymart\\Desktop\\assets\\TopRectangle.png")); // NOI18N
        headerbg.setText("jLabel1");
        jPanel1.add(headerbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, -1));

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        regform.setBackground(new java.awt.Color(255, 255, 255));
        regform.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 3, true));
        regform.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regword.setFont(new java.awt.Font("Rockwell", 0, 30)); // NOI18N
        regword.setForeground(new java.awt.Color(0, 102, 153));
        regword.setText("Registration Form");
        regform.add(regword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lastname.setFont(new java.awt.Font("Javanese Text", 0, 20)); // NOI18N
        lastname.setText("Last Name");
        regform.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 98, 130), 2));
        regform.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, 25));

        firstname.setFont(new java.awt.Font("Javanese Text", 0, 20)); // NOI18N
        firstname.setText("First Name");
        regform.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 98, 130), 2));
        regform.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 170, 25));

        middleinitial.setFont(new java.awt.Font("Javanese Text", 0, 20)); // NOI18N
        middleinitial.setText("Middle Initial");
        regform.add(middleinitial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 98, 130), 2));
        regform.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 80, 25));

        jLabel9.setFont(new java.awt.Font("Javanese Text", 0, 17)); // NOI18N
        jLabel9.setText("House No.");
        regform.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 98, 130), 2));
        regform.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 170, 25));

        jLabel4.setFont(new java.awt.Font("Javanese Text", 0, 17)); // NOI18N
        jLabel4.setText("Street");
        regform.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 98, 130), 2));
        regform.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 80, 25));

        jLabel10.setFont(new java.awt.Font("Javanese Text", 0, 20)); // NOI18N
        jLabel10.setText("Gender");
        regform.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Javanese Text", 0, 20)); // NOI18N
        jLabel8.setText("Address");
        regform.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 98, 130), 2));
        regform.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 170, 25));

        jLabel11.setFont(new java.awt.Font("Javanese Text", 0, 20)); // NOI18N
        jLabel11.setText("Contact #");
        regform.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, -1, -1));

        jRadioButton1.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        regform.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jRadioButton2.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        regform.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        jTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 98, 130), 2));
        regform.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 170, 25));

        jLabel13.setFont(new java.awt.Font("Javanese Text", 0, 20)); // NOI18N
        jLabel13.setText("Age");
        regform.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jTextField10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 98, 130), 2));
        regform.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 170, 25));

        jLabel14.setFont(new java.awt.Font("Javanese Text", 0, 20)); // NOI18N
        jLabel14.setText("Place of Birth");
        regform.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, -1));

        jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 98, 130), 2));
        regform.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 170, 25));

        jButton5.setBackground(new java.awt.Color(13, 76, 146));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Update");
        regform.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, 120, 43));

        jLabel15.setFont(new java.awt.Font("Javanese Text", 0, 20)); // NOI18N
        jLabel15.setText("Years of Stay");
        regform.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jButton7.setBackground(new java.awt.Color(13, 76, 146));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Clear");
        regform.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 120, 43));

        jButton8.setBackground(new java.awt.Color(13, 76, 146));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Add");
        regform.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 120, 43));

        background.add(regform, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 670, 620));

        regform1.setBackground(new java.awt.Color(255, 255, 255));
        regform1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 3, true));
        regform1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        background.add(regform1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 670, 620));

        jButton1.setBackground(new java.awt.Color(13, 76, 146));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        background.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton3.setBackground(new java.awt.Color(13, 76, 146));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Generate I.D");
        background.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton2.setBackground(new java.awt.Color(13, 76, 146));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Delete");
        background.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResidentDataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResidentDataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResidentDataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResidentDataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResidentDataForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel firstname;
    private javax.swing.JLabel headerbg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lastname;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel middleinitial;
    private javax.swing.JPanel regform;
    private javax.swing.JPanel regform1;
    private javax.swing.JLabel regword;
    // End of variables declaration//GEN-END:variables
}
